from __future__ import annotations

from typing import Protocol


class KeyValueRepository(Protocol):
    async def get(self, key: str) -> bytes | None: ...
    async def set(self, key: str, value: bytes, *, ttl_seconds: int | None = None) -> None: ...
    async def delete(self, key: str) -> bool: ...
