apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinelsiem-backend
  namespace: sentinelsiem
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: sentinelsiem-backend

  template:
    metadata:
      labels:
        app: sentinelsiem-backend

    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: backend
          image: sentinelsiem/backend:0.1.0
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8000

          envFrom:
            - configMapRef:
                name: sentinelsiem-config
            - secretRef:
                name: sentinelsiem-secrets

          env:
            - name: SIEM_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: sentinelsiem-secrets
                  key: SIEM_DATABASE_URL

          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 4

          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "2"
              memory: 2Gi

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          volumeMounts:
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: tmp
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: sentinelsiem-backend
  namespace: sentinelsiem
spec:
  selector:
    app: sentinelsiem-backend

  ports:
    - name: http
      port: 8000
      targetPort: http

  type: ClusterIP